CREATE SCHEMA test; 

CREATE TABLE ds.ft_balance_f (
    "ON_DATE" DATE NOT NULL,
    "ACCOUNT_RK" BIGINT NOT NULL,
    "CURRENCY_RK" BIGINT,
    "BALANCE_OUT" DOUBLE PRECISION,
    PRIMARY KEY ("ON_DATE", "ACCOUNT_RK")
);

CREATE TABLE ds.ft_posting_f (
    "OPER_DATE" DATE NOT NULL,
    "CREDIT_ACCOUNT_RK" BIGINT NOT NULL,
    "DEBET_ACCOUNT_RK" BIGINT NOT NULL,
    "CREDIT_AMOUNT" DOUBLE PRECISION,
    "DEBET_AMOUNT" DOUBLE PRECISION
);

CREATE TABLE ds.md_account_d (
    "DATA_ACTUAL_DATE" DATE NOT NULL,
    "DATA_ACTUAL_END_DATE" DATE NOT NULL,
    "ACCOUNT_RK" INT NOT NULL,
    "ACCOUNT_NUMBER" VARCHAR(20) NOT NULL,
    "CHAR_TYPE" VARCHAR(1) NOT NULL,
    "CURRENCY_RK" INT NOT NULL,
    "CURRENCY_CODE" INT,
    PRIMARY KEY ("DATA_ACTUAL_DATE", "ACCOUNT_RK")
);

CREATE TABLE ds.md_currency_d (
    "CURRENCY_RK" BIGINT NOT NULL,
    "DATA_ACTUAL_DATE" DATE NOT NULL,
    "DATA_ACTUAL_END_DATE" DATE,
    "CURRENCY_CODE" VARCHAR(3),
    "CODE_ISO_CHAR" VARCHAR(3),
    PRIMARY KEY ("CURRENCY_RK", "DATA_ACTUAL_DATE")
);

CREATE TABLE ds.md_exchange_rate_d (
    "DATA_ACTUAL_DATE" DATE NOT NULL,
    "DATA_ACTUAL_END_DATE" DATE,
    "CURRENCY_RK" BIGINT NOT NULL,
    "REDUCED_COURCE" DOUBLE PRECISION,
    "CODE_ISO_NUM" VARCHAR(3),
    PRIMARY KEY ("DATA_ACTUAL_DATE", "CURRENCY_RK")
);

CREATE TABLE ds.md_ledger_account_s (
    "CHAPTER" CHAR(1),
    "CHAPTER_NAME" VARCHAR(16),
    "SECTION_NUMBER" INTEGER,
    "SECTION_NAME" VARCHAR(22),
    "SUBSECTION_NAME" VARCHAR(21),
    "LEDGER1_ACCOUNT" INTEGER,
    "LEDGER1_ACCOUNT_NAME" VARCHAR(47),
    "LEDGER_ACCOUNT" INTEGER NOT NULL,
    "LEDGER_ACCOUNT_NAME" VARCHAR(153),
    "CHARACTERISTIC" CHAR(1),
    "START_DATE" DATE NOT NULL,
    "END_DATE" DATE,
    PRIMARY KEY ("LEDGER_ACCOUNT", "START_DATE")
);







drop table ds.md_exchange_rate_d;

ALTER TABLE ds.md_account_d
DROP CONSTRAINT pk_md_account_d;
SELECT 
    conname AS constraint_name,
    contype AS constraint_type
FROM 
    pg_constraint
WHERE 
    conrelid = 'md_account_d'::regclass;
